# Go test workflow
name: actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build App
      run: make eigenda-proxy

  go-test:
    outputs:
      COVERAGE: ${{ steps.unit.outputs.coverage }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install project dependencies
      run: | 
        go mod download

    - name: Run Unit Tests
      id: unit
      run: | 
        make test 

    - name: Run Optimism Test
      run: | 
        make optimism-test

  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  holesky-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install project dependencies
      run: | 
        go mod download
    - name: Run holesky tests
      env: 
        SIGNER_PRIVATE_KEY:  ${{ secrets.SIGNER_PRIVATE_KEY }}
      run: | 
        SIGNER_PRIVATE_KEY=$SIGNER_PRIVATE_KEY make holesky-test